namespace CatchUpPlatform.API.News.Interfaces.REST.Resources;
  /// <summary>
  /// Resource for a favorite source
  /// </summary>
  /// <param name="Id">The favorite Source ID Generaterd by this API</param>
  /// <param name="NewsApiKey">The API key generated by the news provider</param>
  /// <param name="SourceId">The news source ID</param>
public record FavoriteSourceResource(int Id,string NewsApiKey, string SourceId);
